version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-dump:/mongo-dump
      - ./docker-init-scripts/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh